from datetime import datetime
from markdown import markdownFromFile
from subprocess import call
import os

# update current branch's README.md with a fresh copy from master
call(['git', 'checkout', 'master', '--', 'README.md'])

START_P = "<p style=\"color: #ffffff; background-color: #000000; text-align: left; font-size: 85%\">index.html generated by readme_to_html.py in branch gh-pages</p>"
END_P = "<p style=\"color: #ffffff; background-color: #000000; text-align: right; font-size: 85%\">last updated: {time}</p>"
TITLE = "<title>github/sentriz/reboodt</title>"
FAVICON = """<link href="data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzM0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzPQMzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzEDMzM7AzMzMwMzMzkDMzM4AAAAAAAAAAADMzMzAzMzOwMzMzEAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzEDMzM9AzMzPQMzMzEDMzM0AzMzPQAAAAAAAAAAAzMzMQMzMz0DMzM9AzMzMQAAAAAAAAAAAAAAAAMzMzEDMzM9AzMzPQMzMzEAAAAAAAAAAAMzMz8DMzMxAAAAAAAAAAADMzMxAzMzPQMzMz0DMzMxAAAAAAAAAAADMzM9AzMzPQMzMzEAAAAAAAAAAAAAAAADMzM7AzMzNgAAAAAAAAAAAAAAAAMzMzEDMzM9AzMzPQAAAAAAAAAAAzMzPQMzMz0DMzMxAAAAAAAAAAAAAAAAAzMzNgMzMzsAAAAAAAAAAAAAAAADMzMxAzMzPQMzMz0AAAAAAAAAAAMzMzEDMzM9AzMzPQMzMzEAAAAAAAAAAAMzMzEDMzM/AAAAAAAAAAADMzMxAzMzPQMzMz0DMzMxAAAAAAAAAAAAAAAAAzMzMQMzMz0DMzM9AzMzMQAAAAAAAAAAAzMzPQMzMzQDMzMxAzMzPQMzMz0DMzMxAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMxAzMzOwMzMzMAAAAAAAAAAAMzMzgDMzM5AzMzMwMzMzsDMzMxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMzAzMzPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP//AAD//wAA/f8AAPTvAADm5wAAzvMAAJ75AACfeQAAz3MAAOdnAAD3LwAA/78AAP//AAD//wAA//8AAA==" rel="icon" type="image/x-icon" />"""
    
current_folder = os.path.dirname(__file__)
markdown_file = os.path.join(current_folder, "README.md")
html_file = os.path.join(current_folder, "index.html")

time_format = "%Y/%m/%d %H:%M:%S"
current_time = datetime.now()
time_string = current_time.strftime(time_format)

# write html to file
markdownFromFile(markdown_file, output=html_file, extensions=["markdown.extensions.tables"])

# write header, favicon and title to file
with open(html_file, "r+") as file:
    content = file.read()
    file.seek(0, 0)
    file.write("<head>" + "\n")
    file.write(TITLE + "\n")
    file.write(FAVICON + "\n")
    file.write(START_P + "\n")
    file.write("</head>" + "\n" + content)

# write time to file
with open(html_file, "a") as file:
    file.write("\n")
    file.write(END_P.format(time=time_string))