from markdown import markdownFromFile
from datetime import datetime
import os

START_P = "<p style=\"color: #ffffff; background-color: #000000; text-align: left; font-size: 85%\">index.html generated by readme_to_html.py in branch gh-pages</p>"
END_P = "<p style=\"color: #ffffff; background-color: #000000; text-align: right; font-size: 85%\">last updated: {time}</p>"
    
current_folder = os.path.dirname(__file__)
markdown_file = os.path.join(current_folder, "README.md")
html_file = os.path.join(current_folder, "index.html")

time_format = "%Y/%m/%d %H:%M:%S"
current_time = datetime.now()
time_string = current_time.strftime(time_format)

# write html to file
markdownFromFile(markdown_file, output=html_file)

# write header to file
with open(html_file, 'r+') as file:
    content = file.read()
    file.seek(0, 0)
    file.write(START_P + '\n' + content)

# write time to file
with open(html_file, "a") as file:
    file.write("\n")
    file.write(END_P.format(time=time_string))