admins:
  - Senan
  - sentriz
  - sentriz_android

# add as many as you can handle
servers:

    GeekShed:
        connect: no
        nick: rebooodt
        host: irc.geekshed.net
        port: 6667
        channels:
          - "#drpeen"
        password: jxcn93498
    
    EsperNet:
        connect: no
        nick: reboodt
        host: irc.esper.net
        port: 6667
        channels:
          - "#reboodt"
        password: no